from pycomm3 import LogixDriver
import pyodbc
from datetime import datetime
import settings

sky_net = LogixDriver(settings.sky_net_driver)

con = pyodbc.connect(Trusted_Connection='no',
                     driver='{SQL Server}',
                     server=settings.database_ip,
                     database='Alpha_Live',
                     UID=settings.database_id,
                     PWD=settings.database_password)
cursor = con.cursor()


def build_tuple_from_workstation_tuple(tag_list, workstation_location):
    time_stamp = datetime.now().strftime('%Y-%m-%d %H:%M')
    instance_tuple = (time_stamp, workstation_location)
    for tag in tag_list:
        readout = sky_net.read(tag)[1]
        if readout is True:
            readout = 1
        if readout is False:
            readout = 0
        if isinstance(readout, str):
            pass
        else:
            readout = round(readout, 3)
        instance_tuple = instance_tuple + (readout,)
    return instance_tuple


def insert_tuple_to_table(table_name, instance_tuple):
    cursor.execute('INSERT INTO [dbo].[' + table_name + '] VALUES ' + str(instance_tuple))
    con.commit()


tank_farm_tags = ['ComData_TankFarm_To_Skynet.Status_Bits[0].0',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].1',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].2',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].3',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].4',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].5',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].6',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].7',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].8',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].9',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].10',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].11',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].12',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].13',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].14',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].15',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].16',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].17',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].18',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].19',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].20',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].21',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].22',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].23',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].24',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].25',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].26',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].27',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].28',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].29',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].30',
                  'ComData_TankFarm_To_Skynet.Status_Bits[0].31',
                  'ComData_TankFarm_To_Skynet.Setpoint_Values[0]',
                  'ComData_TankFarm_To_Skynet.Setpoint_Values[1]',
                  'ComData_TankFarm_To_Skynet.Setpoint_Values[2]',
                  'ComData_TankFarm_To_Skynet.Process_Values[0]',
                  'ComData_TankFarm_To_Skynet.Process_Values[1]',
                  'ComData_TankFarm_To_Skynet.Process_Values[2]',
                  'ComData_TankFarm_To_Skynet.Process_Values[3]',
                  'ComData_TankFarm_To_Skynet.Process_Values[4]',
                  'ComData_TankFarm_To_Skynet.Process_Values[5]',
                  'ComData_TankFarm_To_Skynet.Process_Values[6]',
                  'ComData_TankFarm_To_Skynet.Process_Values[7]',
                  'ComData_TankFarm_To_Skynet.Process_Values[8]',
                  'ComData_TankFarm_To_Skynet.Process_Values[9]',
                  'ComData_TankFarm_To_Skynet.Process_Values[10]',
                  'ComData_TankFarm_To_Skynet.Process_Values[11]',
                  'ComData_TankFarm_To_Skynet.Process_Values[12]',
                  'ComData_TankFarm_To_Skynet.Process_Values[13]',
                  'ComData_TankFarm_To_Skynet.Process_Values[19]',
                  'ComData_TankFarm_To_Skynet.Process_Values[20]',
                  'ComData_TankFarm_To_Skynet.Process_Values[21]',
                  'ComData_TankFarm_To_Skynet.Process_Values[22]',
                  'ComData_TankFarm_To_Skynet.Process_Values[23]']

chocotech_kitchen_tags = ['ComData_Chocotech_To_Skynet.Parameters[0]',
                          'ComData_Chocotech_To_Skynet.Parameters[1]',
                          'ComData_Chocotech_To_Skynet.Parameters[2]',
                          'ComData_Chocotech_To_Skynet.Parameters[3]',
                          'ComData_Chocotech_To_Skynet.Parameters[4]',
                          'ComData_Chocotech_To_Skynet.Parameters[5]',
                          'ComData_Chocotech_To_Skynet.Parameters[6]',
                          'ComData_Chocotech_To_Skynet.Parameters[7]',
                          'ComData_Chocotech_To_Skynet.Parameters[8]',
                          'ComData_Chocotech_To_Skynet.Parameters[9]',
                          'ComData_Chocotech_To_Skynet.Parameters[10]',
                          'ComData_Chocotech_To_Skynet.Parameters[11]',
                          'ComData_Chocotech_To_Skynet.Parameters[12]',
                          'ComData_Chocotech_To_Skynet.Parameters[13]',
                          'ComData_Chocotech_To_Skynet.Parameters[14]',
                          'ComData_Chocotech_To_Skynet.Process_Values[0]',
                          'ComData_Chocotech_To_Skynet.Process_Values[1]',
                          'ComData_Chocotech_To_Skynet.Process_Values[2]',
                          'ComData_Chocotech_To_Skynet.Process_Values[3]',
                          'ComData_Chocotech_To_Skynet.Process_Values[4]',
                          'ComData_Chocotech_To_Skynet.Process_Values[5]',
                          'ComData_Chocotech_To_Skynet.Process_Values[6]',
                          'ComData_Chocotech_To_Skynet.Process_Values[7]',
                          'ComData_Chocotech_To_Skynet.Process_Values[8]',
                          'ComData_Chocotech_To_Skynet.Process_Values[9]',
                          'ComData_Chocotech_To_Skynet.Process_Values[10]',
                          'ComData_Chocotech_To_Skynet.Process_Values[11]',
                          'ComData_Chocotech_To_Skynet.Process_Values[12]',
                          'ComData_Chocotech_To_Skynet.Process_Values[13]',
                          'ComData_Chocotech_To_Skynet.Process_Values[14]',
                          'ComData_Chocotech_To_Skynet.Process_Values[15]',
                          'ComData_Chocotech_To_Skynet.Process_Values[16]',
                          'ComData_Chocotech_To_Skynet.Process_Values[17]',
                          'ComData_Chocotech_To_Skynet.Process_Values[18]',
                          'ComData_Chocotech_To_Skynet.Process_Values[19]',
                          'ComData_Chocotech_To_Skynet.Process_Values[20]',
                          'ComData_Chocotech_To_Skynet.Process_Values[21]',
                          'ComData_Chocotech_To_Skynet.Process_Values[22]',
                          'ComData_Chocotech_To_Skynet.Process_Values[23]',
                          'ComData_Chocotech_To_Skynet.Process_Values[24]',
                          'ComData_Chocotech_To_Skynet.Status_Bits[0].10',
                          'ComData_Chocotech_To_Skynet.Status_Bits[0].11',
                          'ComData_Chocotech_To_Skynet.Status_Bits[0].12']

kgm_080_tags = ['ComData_KGM_080_Alpha_To_Skynet.Parameters[0]',
                'ComData_KGM_080_Alpha_To_Skynet.Status_Bits[2]',
                'ComData_KGM_080_Alpha_To_Skynet.Process_Values[0]',
                'ComData_KGM_080_Alpha_To_Skynet.Process_Values[1]',
                'ComData_KGM_080_Alpha_To_Skynet.Process_Values[2]',
                'ComData_KGM_080_Alpha_To_Skynet.Process_Values[3]',
                'ComData_KGM_080_Alpha_To_Skynet.Process_Values[11]',
                'ComData_KGM_080_Alpha_To_Skynet.Process_Values[13]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[1]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[2]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[3]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[4]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[7]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[8]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[9]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[10]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[13]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[14]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[15]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[16]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[17]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[18]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[19]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[20]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[21]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[22]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[23]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[24]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[25]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[26]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[27]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[28]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[30]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[31]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[32]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[35]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[36]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[37]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[38]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[39]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[40]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[41]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[42]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[43]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[44]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[45]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[46]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[47]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[48]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[49]',
                'ComData_KGM_080_Alpha_To_Skynet.Setpoint_Values[50]']

ttb_015_tags = ['ComData_TTB_015_Alpha_To_Skynet.Parameters[0]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[0]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[1]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[2]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[3]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[4]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[5]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[6]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[7]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[8]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[9]',
                'ComData_TTB_015_Alpha_To_Skynet.Process_Values[10]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[0]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[1]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[2]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[3]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[4]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[5]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[6]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[7]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[8]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[9]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[10]',
                'ComData_TTB_015_Alpha_To_Skynet.Setpoint_Values[11]']

m5_090_tags = ['ComData_M5_090_Alpha_To_Skynet.Parameters[0]',
               'ComData_M5_090_Alpha_To_Skynet.Process_Values[8]',
               'ComData_M5_090_Alpha_To_Skynet.Process_Values[9]',
               'ComData_M5_090_Alpha_To_Skynet.Process_Values[10]',
               'ComData_M5_090_Alpha_To_Skynet.Process_Values[11]',
               'ComData_M5_090_Alpha_To_Skynet.Process_Values[0]',
               'ComData_M5_090_Alpha_To_Skynet.Process_Values[1]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[5]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[6]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[7]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[8]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[9]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[10]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[11]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[12]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[13]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[14]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[15]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[16]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[20]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[21]',
               'ComData_M5_090_Alpha_To_Skynet.Setpoint_Values[22]']

tt_100_tags = ['ComData_TT_100_Alpha_To_Skynet.Parameters[0]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[0]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[1]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[2]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[3]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[4]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[5]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[6]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[7]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[8]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[9]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[0]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[1]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[2]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[3]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[4]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[5]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[6]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[7]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[8]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[9]']

m5_140_tags = ['ComData_M5_140_Alpha_To_Skynet.Parameters[0]',
               'ComData_M5_140_Alpha_To_Skynet.Process_Values[8]',
               'ComData_M5_140_Alpha_To_Skynet.Process_Values[9]',
               'ComData_M5_140_Alpha_To_Skynet.Process_Values[10]',
               'ComData_M5_140_Alpha_To_Skynet.Process_Values[11]',
               'ComData_M5_140_Alpha_To_Skynet.Process_Values[20]',
               'ComData_M5_140_Alpha_To_Skynet.Process_Values[21]',
               'ComData_M5_140_Alpha_To_Skynet.Process_Values[22]',
               'ComData_M5_140_Alpha_To_Skynet.Process_Values[23]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[1]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[2]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[3]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[4]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[5]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[6]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[7]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[8]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[9]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[10]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[11]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[20]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[21]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[22]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[23]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[24]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[25]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[30]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[31]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[32]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[33]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[34]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[35]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[36]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[37]',
               'ComData_M5_140_Alpha_To_Skynet.Setpoint_Values[38]']

tt_150_tags = ['ComData_TT_150_Alpha_To_Skynet.Parameters[0]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[0]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[1]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[2]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[3]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[4]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[5]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[6]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[7]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[8]',
               'ComData_TT_100_Alpha_To_Skynet.Process_Values[9]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[0]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[1]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[2]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[3]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[4]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[5]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[6]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[7]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[8]',
               'ComData_TT_100_Alpha_To_Skynet.Setpoint_Values[9]']

dbs_080_tags = ['ComData_DBS_080_Alpha_To_Skynet.Status_Bits[10]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[11]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[12]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[13]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[14]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[15]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[16]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[17]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[18]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[19]',
                'ComData_DBS_080_Alpha_To_Skynet.Status_Bits[20]']

dfr_031_tags = ['ComData_DFR_031_Alpha_To_Skynet.Status_Bits[10]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[11]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[12]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[13]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[14]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[15]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[16]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[17]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[18]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[19]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[20]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[21]',
                'ComData_DFR_031_Alpha_To_Skynet.Status_Bits[22]']

hcm_273_tags = ['ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[9]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[10]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[11]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[12]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[13]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[14]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[15]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[16]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[17]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[18]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[19]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Status_Bits[20]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Process_Values[10]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Process_Values[11]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Process_Values[13]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[10]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[12]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[13]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[14]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[15]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[16]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[17]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[18]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[19]',
                'ComData_HCM_273_2_Alpha_To_Skynet.Status_Bits[20]']

hcm_274_tags = ['ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[9]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[10]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[11]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[12]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[13]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[14]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[15]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[16]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[17]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[18]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[19]',
                'ComData_HCM_274_1_Alpha_To_Skynet.Status_Bits[20]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Process_Values[10]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Process_Values[11]',
                'ComData_HCM_273_1_Alpha_To_Skynet.Process_Values[13]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[10]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[12]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[13]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[14]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[15]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[16]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[17]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[18]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[19]',
                'ComData_HCM_274_2_Alpha_To_Skynet.Status_Bits[20]']

ttm_147_tags = ['ComData_TTM_147_1_Alpha_To_Skynet.Status_Bits[10]',
                'ComData_TTM_147_1_Alpha_To_Skynet.Status_Bits[11]',
                'ComData_TTM_147_1_Alpha_To_Skynet.Status_Bits[12]',
                'ComData_TTM_147_1_Alpha_To_Skynet.Status_Bits[13]',
                'ComData_TTM_147_1_Alpha_To_Skynet.Status_Bits[14]',
                'ComData_TTM_147_1_Alpha_To_Skynet.Process_Values[10]',
                'ComData_TTM_147_1_Alpha_To_Skynet.Process_Values[11]',
                'ComData_TTM_147_1_Alpha_To_Skynet.Process_Values[12]',
                'ComData_TTM_147_1_Alpha_To_Skynet.Process_Values[13]',
                'ComData_TTM_147_1_Alpha_To_Skynet.Process_Values[14]']

sn_bagger_tags = ['ComData_SN_To_Skynet.Process_Values[0]', 'ComData_SN_To_Skynet.Process_Values[1]',
                  'ComData_SN_To_Skynet.Process_Values[2]', 'ComData_SN_To_Skynet.Process_Values[3]',
                  'ComData_SN_To_Skynet.Process_Values[4]', 'ComData_SN_To_Skynet.Process_Values[5]',
                  'ComData_SN_To_Skynet.Process_Values[8]', 'ComData_SN_To_Skynet.Process_Values[9]',
                  'ComData_SN_To_Skynet.Process_Values[11]', 'ComData_SN_To_Skynet.Process_Values[20]',
                  'ComData_SN_To_Skynet.Parameters[0]', 'ComData_SN_To_Skynet.String_Data[0]']

site_tag_dic = {'Tank Farm': tank_farm_tags, 'Chocotech Kitchen': chocotech_kitchen_tags, 'KGM 080': kgm_080_tags,
                'TTB 015': ttb_015_tags, 'M5 090': m5_090_tags, 'TT 100': tt_100_tags, 'M5 140': m5_140_tags,
                'TT 150': tt_150_tags, 'DBS 080': dbs_080_tags, 'DFR 031': dfr_031_tags, 'HCM 273': hcm_273_tags,
                'HCM 274': hcm_274_tags, 'TTM 147': ttm_147_tags, 'SN Bagger': sn_bagger_tags}

for tag_instance in site_tag_dic:
    try:
        insert_tuple_to_table(tag_instance, build_tuple_from_workstation_tuple(site_tag_dic[tag_instance], tag_instance))
    except Exception:
        print(tag_instance)
